# Generated by Django 5.2.14 on 2026-05-24 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='momo_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='momo_provider',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('vod', 'Vodafone Cash'), ('atl', 'AirtelTigo Money')], default='mtn', max_length=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
