# Generated by Django 5.2.14 on 2026-08-16 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0002_alter_handout_options_handout_department'),
        ('payments', '0002_remove_payment_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='handout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='handouts.handout'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['handout', 'status'], name='payments_pa_handout_30389d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'successful')), fields=('student', 'handout'), name='one_successful_payment_per_handout'),
        ),
    ]
