# Generated by Django 5.2.14 on 2026-08-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('handouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='handout',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='department.department'),
        ),
    ]
